export const ADD_PLAYLIST="ADD_PLAYLIST";
export const REMOVE_PLAYLIST="REMOVE_PLAYLIST";
export const LIST_PLAYLIST_REQUEST="LIST_PLAYLIST_REQUEST";
export const LIST_PLAYLIST_SUCCESS="LIST_PLAYLIST_SUCCESS";
export const PLAYLIST_ERROR="PLAYLIST_ERROR";
export const PLAYLIST_CLEAR="PLAYLIST_CLEAR";