export const ADD_SONG_TO_PLAYLIST="ADD_SONG_TO_PLAYLIST";
export const REMOVE_SONG_FROM_PLAYLIST="REMOVE_SONG_FROM_PLAYLIST";
export const EMPTY_PLAYLIST="EMPTY_PLAYLIST";
export const LIST_PLAYLIST_SONGS_REQUEST="LIST_PLAYLIST_SONGS_REQUEST";
export const LIST_PLAYLIST_SONGS_SUCCESS="LIST_PLAYLIST_SONGS_SUCCESS";
export const PLAYLIST_ERROR="PLAYLIST_ERROR";
