export const ADD_TO_FAVOURITE="ADD_TO_FAVOURITE";
export const REMOVE_FROM_FAVOURITE="REMOVE_FROM_FAVOURITE";
export const FAVOURITE_ERROR="FAVOURITE_ERROR";
export const CLEAR_FAVOURITE="CLEAR_FAVOURITE";
export const LIST_FAVOURITE_REQUEST="LIST_FAVOURITE_REQUEST";
export const LIST_FAVOURITE_SUCCESS="LIST_FAVOURITE_SUCCESS";